### PR TITLE
Specifying minimum value amount

### PR DESCRIPTION
**Pull request by haikuginger**
It's important for people to know what their rights are.

### CODE REVIEW

**Comment by jMyles** [comment]
Yeah I kinda wrestled with this one in my mind.  There's no way to codify inflation (although I think in a just world we can move beyond inflation).  But $20?!

**Comment by haikuginger** [comment]
Hey, I don't write the laws.

**Comment by jMyles** [comment]
Well, rewriting it in plain language probably means doing a tiny bit of interpretation on what "$20" really means in a document drafted in the 18th century.  Assuming that this value is about $1,500 or so today, how about we say, ("for example, more than the value of a <x> or a <y>")?

**Comment by haikuginger** [comment]
Hmm. I suppose the question is whether we want to preserve "what the Bill of Rights would mean if it was being written today" or "what the Bill of Rights, as passed in 1789, means in modern language". Given that the article doesn't actually account for inflation, it's a big difference in this particular case (and a good example of why coding for modularity is a good idea).

**Pull request closed without merging**
